### ISSUE TITLE
Supporting Edits with EtherCIS

### ISSUE THREAD

**Issue by tony-shannon** [ethercis/ethercis#67] opened 2017-10-12 16:12 UTC
Our Ripple showcase stack supports Create & Reads of key clinical data types with EtherCIS
We now need to move to supporting Edits also.
Info is that there is an issue with Edits..
@freshehr could you elaborate what needs to be done from your perspective
@chevalleyc could you please outline the effort involved? 
thanks ..

**Comment by chevalleyc** [comment] 2017-10-13 01:53
I'm not sure I understand the issue. On a client perspective, what is the transaction? Is it an Update? Is it possible to get a sample REST transaction example with the corresponding template and existing test data?

**Comment by freshehr** [comment] 2017-10-13 06:18
I have some rest samples but I'm on my phone only for a few hours. The
problem is that the PUT works but does not increment the composition
version.
Samples later

On 13 Oct 2017 at 03:05, <Christian Chevalley <notifications@github.com>>
wrote:

I'm not sure I understand the issue. On a client perspective, what is the
transaction? Is it an Update? Is it possible to get a sample REST
transaction example with the corresponding template and existing test data?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ethercis/ethercis/issues/67#issuecomment-336328353>,
or mute
the thread

**Comment by tony-shannon** [comment] 2017-10-13 11:43
thanks Ian @freshehr 
@chevalleyc please let us know if this info from Ian provides enough to solve this one, 
thanks

**Comment by chevalleyc** [comment] 2017-10-15 03:29
Thanks @freshehr got enough information. I will try to fix it before going to Japan...

**Comment by tony-shannon** [comment] 2017-10-15 13:23
thanks Christian
T

**Comment by dileep-ehr** [comment] 2017-10-16 12:12
I feel that #30 is also related to this issue. If the update includes a change of the composer, it is not done. The original composer is returned with the new version.

**Comment by chevalleyc** [comment] 2017-10-16 14:48
Thanks for all the feedback. I checked these issues today (all more or less related) and could figure out the missing bits and bad assumptions. I don't think I can post a fix before leaving for Japan though, but this will be fixed week 30/10. Many thanks again

**Comment by tony-shannon** [comment] 2017-10-16 15:04
ok thanks for the update Christian @chevalleyc

**Comment by chevalleyc** [comment] 2017-11-01 08:40
I have uploaded a fix and updated the server libraries. Please let me know.

**Comment by freshehr** [comment] 2017-11-02 14:49
Confirmed working correctly.

**Closed** 2017-11-03 01:45 UTC
Labels: bug
