### ISSUE TITLE
Not able to add new composition for a template

### ISSUE THREAD

**Issue by kotreshbandri** [ethercis/ethercis#50] opened 2017-09-29 11:39 UTC
When i tried to add composition for a template i'm getting following error.

error:-

**HTTP ERROR: 500

Problem accessing /ehr//rest/v1/composition. Reason:

    #1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: Could not convert JSON map:java.lang.ClassCastException: class com.marand.thinkehr.f.a.b.k not an enum
[OPT and composition json.zip](https://github.com/ethercis/ethercis/files/1344184/OPT.and.composition.json.zip)
**

Here i had attached template and composition in compressed format

**Comment by freshehr** [comment] 2017-09-29 14:38
Hi,

I have not looked at the template yet but a quick look at the json makes me think that your coding of cause_of_death is wrong

The v2 family history archetype says


at0014::Cause of death? Choice Optional | Relationship of the problem/diagnosis to the death of this family member. | Choice of: Coded Textat0061::Direct cause or closely related [The problem or diagnosis was a direct cause or closely related to the direct cause of death.]at0062::Unrelated [The problem or diagnosis was unrelated to the cause of death.]at0063::Indeterminate [It is impossible to determine whether the problem or diagnosis was closely related to the direct cause of death.]
-- | -- | --

so your json would need ot be 

  "family_history/family_history:0/family_history:0/per_family_member:0/clinical_history:0/cause_of_death|code": "at0062",
      "family_history/family_history:0/family_history:0/per_family_member:0/clinical_history:0/cause_of_death|value": "Unrelated",
      "family_history/family_history:0/family_history:0/per_family_member:0/clinical_history:0/cause_of_death|terminology": "local",

The coding used must match the allowed atCodes if you use 'local' as the terminology.

**Comment by dileep-ehr** [comment] 2017-09-30 05:54
Tried the feedback from Ian and still getting the same error.

BTW, the template is also not returning the FLAT example json. After unusual delay, the api call returns '200 OK' but content is empty. Looks like Ethercis isnot responding and it is timing out at the NGINX proxy.

The ECISFLAT example is returned properly

**Comment by freshehr** [comment] 2017-10-01 11:00
I built an identical (as far as I can tell) template using Encounter composition, Family history section and family history v2 evaluation and everything works. 

The fact that the Example composition is not being returned makes me think that something may be messed up with your .opt. 

Can you send the .oet and archetypes via TD->Export Fileset and I will try to reproduce here?

Ian

**Comment by dileep-ehr** [comment] 2017-10-01 12:22
I also created a new template exactly like the one with problem and it
works.

As said, the problem could be some corruption in opt. It works now. Would
you still be interested in getting the problem oet?


Dileep V S
Founder
HealtheLife Ventures LLP
+91 9632888113
103, Innovation Centre, IIIT, Electronics City, Bangalore 560100,
healthelife.in

On 01-Oct-2017 4:30 PM, "Ian McNicoll" <notifications@github.com> wrote:

I built an identical (as far as I can tell) template using Encounter
composition, Family history section and family history v2 evaluation and
everything works.

The fact that the Example composition is not being returned makes me think
that something may be messed up with your .opt.

Can you send the .oet and archetypes via TD->Export Fileset and I will try
to reproduce here?

Ian

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ethercis/ethercis/issues/50#issuecomment-333368896>,
or mute
the thread

**Comment by tony-shannon** [comment] 2017-10-13 11:12
closing this @dileep-ehr on advice from @chevalleyc  , please reopen if any related issues

**Closed by tony-shannon** 2017-10-13 11:12 UTC
