### ISSUE TITLE
Not sure if this is an error in AQL Path and/or data for Vital Signs

### ISSUE THREAD

**Issue by robtweed** [ethercis/ethercis#139] opened 2018-07-17 15:48 UTC
I have a problem parsing this - template is Vital Signs

Take this AQL Path within the introspection document:

"aql_path": "/content[openEHR-EHR-SECTION.vital_signs.v1]/items[openEHR-EHR-OBSERVATION.indirect_oximetry.v1]/data[at0001]/events[at0002]/data[at0003]/items[at0006]/value"

Here's an example of a patient having data for that:

"archetype_node_id": "openEHR-EHR-SECTION.vital_signs.v1",
        "@class": "SECTION",
        "items": [{
            "archetype_node_id": "openEHR-EHR-OBSERVATION.indirect_oximetry.v1",
            "@class": "OBSERVATION",
            "data": {
                "events": [{
                    "archetype_node_id": "at0002",
                    "time": {
                        "value": {
                            "value": "2018-02-15T11:23:42.000Z",
                            "epoch_offset": 1518693822000
                        },
                        "@class": "DV_DATE_TIME"
                    },
                    "data": {
                        "archetype_node_id": "at0003",
                        "items": [{
                            "archetype_node_id": "at0006",
                            "value": {
                                "type": "PERCENT",
                                "accuracy": 0,
                                "numerator": 2,
                                "precision": 0,
                                "denominator": 100,
                                "accuracy_percent": false
                            },
                            "@class": "ELEMENT"
                        }]
                    },
                    "@class": "POINT_EVENT"
                }],
                "name": {
                    "value": "Event Series"
                },
                "origin": {
                    "value": {
                        "value": "2018-02-15T11:23:42.000Z",
                        "epoch_offset": 1518693822000
                    },
                    "@class": "DV_DATE_TIME"
                }
            }
        }],
        "name": {
            "value": "Vital Signs Observations"
        }
    }]

The problem in the AQL path is this bit:

    data[at0001]

because the data array element doesn't have an archetype_node_id specified at all, so my parser can't find the "at0001' and gives up

Any ideas?

Rob

**Comment by freshehr** [comment] 2018-07-17 17:08
Looks like an issue in the way that the data is being represented.

Should be more like

```
 "data": {
                            "@class": "HISTORY",
                            "name": {
                                "@class": "DV_TEXT",
                                "value": "history"
                            },
                            "archetype_node_id": "at0001",
                            "origin": {
                                "@class": "DV_DATE_TIME",
                                "value": "2017-05-31T00:23:02.518+02:00"
                            },
```

The top-level structure in an Observation class is the HISTORY class.
THe canonical XML equivalent is 

 <data archetype_node_id="at0001">
                    <name>
                        <value>history</value>
                    </name>
                    <origin>
                        <value>2017-05-31T00:23:02.518+02:00</value>
                    </origin>

Note that the way that origin/value is handled is also incorrect (I think).

It shoud be origin/value and not origin/value/value. I think the issue is that Ethercis also wants to carry epoch_onset but that is not part of the RM and should arguably not be there at all and certainly not disrupting the expected path to the data value.

I'm not so bothered about omitting the @class designators when these are fixed in the RM (or default).

**Comment by chevalleyc** [comment] 2018-07-18 01:29
Could you please post:

- expected behavior and actual behavior
- step to reproduce the issue (AQL query in your case I guess)

Thanks

PS. re epoch_offset it is there as a workaround to the very rudimentary data types supported by JSON.

**Comment by robtweed** [comment] 2018-07-18 09:33
This data is what comes back from the "top-level AQL":

230: request to ethercis: {"url":"http://178.62.71.220:8080/rest/v1/query","method":"POST","json":true,"headers":{"Ehr-Session":"sessionId:127.0.0.1-guest-1531841153764-1127305792-526"},"body":{"aql":"select a as data from EHR e[ehr_id/value='cd8abecd-9925-4313-86af-93aab4930eae'] contains COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1] where a/name/value='Vital Signs Observations'"}}

The problem is in the first Vitals record in the resultset that is returned (though probably in other records too)

As Ian has confirmed, I was expecting this within the data array element:

                            "archetype_node_id": "at0001",

to match the AQL Path returned by the introspection report for the template:

"aql_path": "/content[openEHR-EHR-SECTION.vital_signs.v1]/items[openEHR-EHR-OBSERVATION.indirect_oximetry.v1]/**data[at0001]**/events[at0002]/data[at0003]/items[at0006]/value"

but my original post shows what comes back (as you'll see when you run that AQL)

Rob

**Comment by robtweed** [comment] 2018-07-19 08:30
and here's what it now looks like

[broken.txt](https://github.com/ethercis/ethercis/files/2209024/broken.txt)

**Comment by chevalleyc** [comment] 2018-07-19 08:46
Could you please post the corresponding AQL?

**Comment by chevalleyc** [comment] 2018-07-20 01:46
Uploaded a fix, now the missing Cholecystectomy (and other stuff) should be there:

```
            "data": {
                "@class": "COMPOSITION",
                "content": [
                    {
                        "archetype_node_id": "openEHR-EHR-SECTION.problems_issues_rcp.v1",
                        "@class": "SECTION",
                        "items": [
                            {
                                "archetype_node_id": "openEHR-EHR-EVALUATION.problem_diagnosis.v1",
                                "@class": "EVALUATION",
                                "data": {
                                    "archetype_node_id": "at0001",
                                    "items": [
                                        {
                                            "archetype_node_id": "at0002",
                                            "value": {
                                                "value": "Cholecystectomy",
                                                "defining_code": {
                                                    "code_string": "00001",
                                                    "terminology_id": {
                                                        "name": "local",
                                                        "value": "local"
                                                    }
                                                }
                                            },
                                            "@class": "ELEMENT"
                                        },
                                        {
                                            "archetype_node_id": "at0009",
                                            "value": {
                                                "value": "Working"
                                            },
                                            "@class": "ELEMENT"
                                        },
                                        {
                                            "archetype_node_id": "at0077",
                                            "value": {
                                                "value": "2017-04-11T00:00:00.000+01:00",
                                                "epoch_offset": 1491865200000
                                            },
                                            "@class": "ELEMENT"
                                        }
                                    ]
                                }
                            }
                        ],
                        "name": {
                            "value": "Problem list"
                        }
                    }
                ],
```

**Comment by robtweed** [comment] 2018-07-20 14:14
OK so the headings used in Helm are now coming back as before, but there are still other problems in Vital Signs.

Running the AQL that Ian has specified here:
  https://github.com/RippleOSI/Ripple-openEHR/blob/master/docs/bindings/Current%20Ripple%20Headings/Vital%20signs/Vital%20signs.md

for patient 9999999000 (Ivor Cox), returns all the fields, eg:

       {
               "uid": "0233a61f-c63a-4eca-b49c-88ecbcf840bc::vm01.ethercis.org::1",
               "systolic": "2.0",
               "diastolic": "2.0",
               "onAir": "true",
               "respiratoryRate": "2.0",
               "heartRate": "2.0",
               "author": "bob.smith@gmail.com",
               "date_created": "2018-02-15T11:23:42Z",
               "oxygenSats": "2.0",
               "temperature": "2.0",
               "levelOfConsciousnessCode": "at0006",
               "newsScore": "20"
           }

However the "Top Level" AQL appears to only return the indirect_oximetry data and nothing else:

 {
      "data": {
        "@class": "COMPOSITION",
        "content": [
          {
            "archetype_node_id": "openEHR-EHR-SECTION.vital_signs.v1",
            "@class": "SECTION",
            "items": [
              {
                "archetype_node_id": "openEHR-EHR-OBSERVATION.indirect_oximetry.v1",
                "@class": "OBSERVATION",
                "data": {
                  "events": [
                    {
                      "archetype_node_id": "at0002",
                      "time": {
                        "value": "2018-02-15T11:23:42.000Z",
                        "@class": "DV_DATE_TIME"
                      },
                      "data": {
                        "archetype_node_id": "at0003",
                        "items": [
                          {
                            "archetype_node_id": "at0006",
                            "value": {
                              "type": "PERCENT",
                              "accuracy": 0,
                              "numerator": 2,
                              "precision": 0,
                              "denominator": 100,
                              "accuracy_percent": false
                            },
                            "@class": "ELEMENT"
                          }
                        ]
                      },
                      "@class": "POINT_EVENT"
                    }
                  ],
                  "name": {
                    "value": "Event Series"
                  },
                  "origin": {
                    "value": "2018-02-15T11:23:42.000Z",
                    "@class": "DV_DATE_TIME"
                  },
                  "archetype_node_id": "at0001"
                }
              }
            ],
            "name": {
              "value": "Vital Signs Observations"
            }
          }
        ],
        "context": {
          "@class": "EVENT_CONTEXT",
          "setting": {
            "value": "other care",
            "@class": "DV_CODED_TEXT",
            "defining_code": {
              "@class": "CODE_PHRASE",
              "code_string": "238",
              "terminology_id": {
                "value": "openehr",
                "@class": "TERMINOLOGY_ID"
              }
            }
          },
          "start_time": {
            "value": "2018-02-15T11:23:42UTC",
            "@class": "DV_DATE_TIME"
          },
          "health_care_facility": {
            "name": "Rippleburgh GP Practice",
            "@class": "PARTY_IDENTIFIED",
            "external_ref": {
              "id": {
                "value": "999999-345",
                "@class": "GENERIC_ID",
                "scheme": "2.16.840.1.113883.2.1.4.3"
              },
              "type": "PARTY",
              "@class": "PARTY_REF",
              "namespace": "NHS-UK"
            }
          }
        },
        "category": {
          "value": "Event",
          "@class": "DV_CODED_TEXT",
          "defining_code": {
            "@class": "CODE_PHRASE",
            "code_string": "433",
            "terminology_id": {
              "value": "openehr",
              "@class": "TERMINOLOGY_ID"
            }
          }
        },
        "composer": {
          "name": "bob.smith@gmail.com",
          "@class": "PARTY_IDENTIFIED"
        },
        "language": {
          "@class": "CODE_PHRASE",
          "code_string": "en",
          "terminology_id": {
            "value": "ISO_639-1",
            "@class": "TERMINOLOGY_ID"
          }
        },
        "territory": {
          "@class": "CODE_PHRASE",
          "code_string": "GB",
          "terminology_id": {
            "value": "ISO_3166-1",
            "@class": "TERMINOLOGY_ID"
          }
        },
        "uid": {
          "@class": "OBJECT_VERSION_ID",
          "value": "0233a61f-c63a-4eca-b49c-88ecbcf840bc::vm01.ethercis.org::1"
        }
      }
    },

Here's an example of the Top Level Query:

{"url":"http://178.62.71.220:8080/rest/v1/query","method":"POST","json":true,"headers":{"Ehr-Session":"sessionId:127.0.0.1-guest-1532093676693-364625327-230"},"body":{"aql":"select a as data from EHR e[ehr_id/value='cd8abecd-9925-4313-86af-93aab4930eae'] contains COMPOSITION a[openEHR-EHR-COMPOSITION.encounter.v1] where a/name/value='Vital Signs Observations'"}}

**Comment by chevalleyc** [comment] 2018-07-23 02:59
Thanks Rob, I've uploaded a fix dealing with multiple contents as above. Pls check. Many thanks

**Comment by chevalleyc** [comment] 2018-11-01 06:42
Assuming fixed. Pls reopen if needed. Tx

**Closed by chevalleyc** 2018-11-01 06:42 UTC
