### ISSUE TITLE
Objects incorrectly escaped in Resultset objects

### ISSUE THREAD

**Issue by freshehr** [ethercis/ethercis#99] opened 2018-02-05 15:34 UTC
Element and other_participation objects are being returned escaped - I thin all objects should be non-escaped when they appear in resultsets.
```
curl -X POST \
  http://178.62.71.220:8080/rest/v1/query \
  -H 'Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=' \
  -H 'Content-Type: application/json' \
  -H 'Ehr-Session: sessionId:127.0.0.1-guest-1517843496297-170699730-2216' \
  -d '{
  "aql": "select    e/ehr_id/value as ehrId,    e/ehr_status/subject/external_ref/id/value as subjectId,    e/ehr_status/subject/external_ref/namespace as subjectNamespace,    a/context/start_time/value as compositionStartTime,    a/uid/value as compositionId,    a/composer/name as composerName,    a/composer/external_ref/id/value as composerId,    a/composer/external_ref/namespace as composerNamespace,    b_a/uid/value as entryId,    b_a/description[at0001]/items[at0002] as Procedure_name,    b_a/description[at0001]/items[at0048] as Outcome,    b_a/description[at0001]/items[at0006] as Complication,    b_a/description[at0001]/items[at0067] as Procedure_type,    b_a/description[at0001]/items[at0063] as Body_site,    b_a/description[at0001]/items[at0014] as Reason,    b_a/description[at0001]/items[at0005] as Comment,    b_a/other_participations as OtherParticipations,    b_a/time/value as Procedure_time,    b_a/ism_transition/current_state/defining_code/code_string as Status_code,    b_a/ism_transition/careflow_step/defining_code/code_string as Careflow_step_code,    b_a/description[at0001]/items[at0049]/value/value as Description from EHR e contains COMPOSITION a[openEHR-EHR-COMPOSITION.health_summary.v1] contains ACTION b_a[openEHR-EHR-ACTION.procedure.v1] where a/name/value='\''Procedures list'\''and b_a/ism_transition/current_state/defining_code/code_string matches {'\''532'\''}"
}'
```

```
        {
            "composerId": null,
            "Comment": null,
            "compositionStartTime": "2018-01-31T11:43:12Z",
            "Description": "aa",
            "Body_site": null,
            "compositionId": "3ad5dccd-63c5-4444-82a6-b9d17364554d::vm01.ethercis.org::3",
            "Procedure_type": null,
            "ehrId": "cd8abecd-9925-4313-86af-93aab4930eae",
            "OtherParticipations": "{\"mode\": {\"value\": \"not specified\", \"definingCode\": {\"codeString\": \"193\", \"terminologyId\": {\"name\": \"openehr\", \"value\": \"openehr\"}}}, \"function\": {\"value\": \"Performer\"}, \"performer\": {\"name\": \"Performer\"}}",
            "composerName": "bob.smith@gmail.com",
            "subjectId": "9999999000",
            "Reason": null,
            "entryId": null,
            "Careflow_step_code": "at0043",
            "subjectNamespace": "uk.nhs.nhs_number",
            "Outcome": null,
            "Procedure_time": "2017-11-13T13:43:12.000Z",
            "Complication": null,
            "Status_code": "532",
            "Procedure_name": "{\"name\":{\"value\":\"Procedure name\"},\"value\":{\"value\":\"aaqqq\",\"defining_code\":{\"codeString\":\"at0039aaa\",\"terminology_id\":{\"name\":\"SNOMED-CT\",\"value\":\"SNOMED-CT\"}}},\"@class\":\"DV_CODED_TEXT\"}",
            "composerNamespace": null
        }
```

**Comment by chevalleyc** [comment] 2018-02-27 07:47
Since I don't want to mix json representations with tabular data (everything in EtherCIS/SQL is a table, including jsonb postgresql, and rightly so when thinking about future analytics/reporting capabilities). I am planning to introduce resultset export formatters in EtherCIS not only limited to JSON, but also capable to export/import results under XML, CSV, HTML etc.  This will allow to specifically address various client needs without much limitation. This CR is now associated to CR #103.

**Comment by serefarikan** [comment] 2018-02-27 09:08
I'm not sure if I understand this bit:
> Since I don't want to mix json representations with tabular data

As far as I can see, the AQL implementation fetches results which are JSONB subsets of a Composition so the starting point of transformation to any format is JSONB contained in a tabular format. Is not this by design in conflict with the statement above?

**Comment by chevalleyc** [comment] 2018-02-27 09:26
Yes you are right, I typed the above too quickly I guess. 

The JSONB internal representation is a convenience (similarly to using ltree to resolve CONTAINS). As you know, a whole composition is actually a mix of purely relational (SQL) and JSONB. My point is that I think assimilating EtherCIS DB to yet-another JSON DB is reductionist since it's not. The whole concept of this representation is to allow end users, data custodian, to perform freely any kind of queries/reporting/analysis using SQL (known tool) or AQL (learning curve), hence the table principle.

My sentence was not correct in the sense I wanted to mean: "I am not happy to mix json representations with tabular data **in a query resultset**" and at core level (e.g. AQL processing). Sorry for the confusion.

**Comment by chevalleyc** [comment] 2018-11-01 06:35
Think this is now fixed. Please re-open if something needs change related to this CR. Tx

**Closed by chevalleyc** 2018-11-01 06:35 UTC
