### ISSUE TITLE
Please explain what types.jar library is and provide access to its sources

### ISSUE THREAD

**Issue by serefarikan** [ethercis/ethercis#84] opened 2017-12-12 16:45 UTC
This library is included in the Ethercis installer but I could not find any explanations for it. It looks like an xmlbean compiled schema but I'm just speculating. 

Could you please explain what this library is and where/why it is needed? The only place I found it to be used is in the set_template_table.sh script

**Comment by chevalleyc** [comment] 2017-12-14 04:18
As for CR#85. History.

**Comment by tony-shannon** [comment] 2017-12-19 12:49
thanks @chevalleyc 
@serefarikan Christian suggests this can be closed after recent discussion.
Please add any more detail you think is needed before we do so.
This may be the kind of question that could be shared on the etherCIS gitter chatroom
https://gitter.im/Ripple-Foundation/EtherCIS
I'll close this issue shortly
Thanks, T

**Comment by chevalleyc** [comment] 2018-05-14 02:28
Closing this issue due to no activity.  If the issue is not yet resolved or requires additional work, you may reopen it or open a new CR.

**Closed by chevalleyc** 2018-05-14 02:28 UTC
Labels: question
