### ISSUE TITLE
/context/participation gives error

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#34] opened 2017-07-13 07:38 UTC
Hi,

As discussed in #22, I am trying to do a commit as below
```
{
  "/composer|identifier": "1234-5678",
  "/composer|name": "Composer",
  "/context/participation:0|function": "Oncologist",
  "/context/participation:0|name": "Composer",
  "/context/participation:0|identifier": "1234-5678",
  "/context/participation:0|mode": "face-to-face communication::openehr::216",
  "/context/health_care_facility|identifier": "123456-123",
  "/context/health_care_facility|name": "FACILITY",
  "/context/location": "Bangalore",
  "/context/setting": "openehr::238|Other Care|",
  "/context/start_time": "2017-07-13T12:44:37.665+05:30",
  "/context/end_time": "2017-07-13T12:48:37.665+05:30",
  "/category":"openehr::431|persistent|",
  "/language": "en",
  "/territory": "IN"
}
```
and am getting the following error
```
#1.0.0 Invocation exception to method:create:org.jooq.exception.DataAccessException: SQL [insert into &quot;ehr&quot;.&quot;participation&quot; (&quot;event_context&quot;, &quot;performer&quot;, &quot;function&quot;, &quot;mode&quot;, &quot;sys_transaction&quot;) values (?, ?, ?, ?, cast(? as timestamp)) returning &quot;ehr&quot;.&quot;participation&quot;.&quot;id&quot;]; ERROR: insert or update on table &quot;participation&quot; violates foreign key constraint &quot;participation_event_context_fkey&quot;
  Detail: Key (event_context)=(5f4443aa-773f-41ed-8686-5c9742ff6afb) is not present in table &quot;event_context&quot;.
```

**Comment by chevalleyc** [comment] 2017-07-26 04:24
I couldn't reproduce this specific exception, but found there are issues whenever committing an empty content composition with ECISFLAT (an empty content is valid btw).

**Comment by chevalleyc** [comment] 2017-07-26 04:50
I've committed a couple of changes in ehrservice. Could you recompile and give it a try? Thanks

**Comment by dileep-ehr** [comment] 2017-07-26 05:01
Please see another example commit(FLAT format) and error. Hope this will be more helpful. Uses the "HRN Yoga service.v0' template. It commits ok with out the participation context.
```
{
  "ctx/language": "en",
  "encounter/language|code": "en",
  "encounter/language|terminology": "ISO_639-1",
  "encounter/territory": "India",
  "encounter/territory|code": "IN",
  "encounter/territory|terminology": "ISO_3166-1",
  "encounter/context/start_time": "2017-07-12T21:53:16.129+05:30",
  "encounter/context/participation:0|function": "Oncologist",
  "encounter/context/participation:0|name": "Composer",
  "encounter/context/participation:0|identifier": "1234-5678",
  "encounter/context/participation:0|mode": "face-to-face communication::openehr::216",
  "encounter/yoga_service:0/ism_transition/current_state|code": "526",
  "encounter/yoga_service:0/ism_transition/current_state|value": "planned",
  "encounter/yoga_service:0/ism_transition/current_state|terminology": "openehr",
  "encounter/yoga_service:0/ism_transition/careflow_step|code": "at0002",
  "encounter/yoga_service:0/ism_transition/careflow_step|value": "Service planned",
  "encounter/yoga_service:0/ism_transition/careflow_step|terminology": "local",
  "encounter/yoga_service:0/service_name|code": "at0.30",
  "encounter/yoga_service:0/service_name|value": "Yoga",
  "encounter/yoga_service:0/service_name|terminology": "local",
  "encounter/yoga_service:0/asanas_done": "Suryanamaskaram",
  "encounter/yoga_service:0/yoga_style|code": "at0.40",
  "encounter/yoga_service:0/yoga_style|value": "Hatha",
  "encounter/yoga_service:0/yoga_style|terminology": "local",
  "encounter/yoga_service:0/scheduled_date_time": "2017-07-25T12:00:00.000+05:30",
  "encounter/yoga_service:0/scheduled_duration|magnitude": 60.0,
  "encounter/yoga_service:0/scheduled_duration|unit": "min",
  "encounter/yoga_service:0/posture_correction": true,
  "encounter/yoga_service:0/facility": "Yoga place 1",
  "encounter/yoga_service:0/participation_mode|code": "at0.33",
  "encounter/yoga_service:0/participation_mode|value": "Single",
  "encounter/yoga_service:0/participation_mode|terminology": "local",
  "encounter/composer|id": "1234-5678",
  "encounter/composer|id_scheme": "userId",
  "encounter/composer|id_namespace": "EHR.NETWORK",
  "encounter/composer|name": "Dileep"
}
```
Error as below
`#1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: Could not convert JSON map:com.marand.thinkehr.f.b.b.a: Unknown segment: participation:0|function! (path: encounter/context/participation:0|function`

Tried removing the participation lines one by one and got similar errors for all the 4 lines.

**Comment by chevalleyc** [comment] 2017-07-26 05:22
Have you tried to commit using ECISFLAT by chance?

**Comment by dileep-ehr** [comment] 2017-07-26 06:00
Please see details below
```
{
  "/composer|identifier": "1234-5678",
  "/composer|name": "Composer",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[at0.31]|value": "0,min",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[at0.48]|value": "local::at0.49|First timer|",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[at0.53]|value": "0,min",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[at0011.1]|value": "local::at0.30|Yoga|",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[at0012]|value": "DEFAULT_TEXT_VALUE",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[at0013]|value": "DEFAULT_TEXT_VALUE",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[at0014.1]|value": "DEFAULT_TEXT_VALUE",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[at0021]|value": "0",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[at0025.1]|value": "1900-01-01T00:00:00Z",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[openEHR-EHR-CLUSTER.feedback.v0]/items[at0001]|value": "0",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[openEHR-EHR-CLUSTER.feedback.v0]/items[at0002]|value": "DEFAULT_TEXT_VALUE",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/description[at0001]/items[openEHR-EHR-CLUSTER.feedback.v0]/items[at0003]|value": "DEFAULT_TEXT_VALUE",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/ism_transition/careflow_step|value": "local::at0002|Service planned|",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/ism_transition/current_state|value": "openehr::526|planned|",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/protocol[at0015]/items[at0.54]|value": "true",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/protocol[at0015]/items[at0.55]|value": "DEFAULT_TEXT_VALUE",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/protocol[at0015]/items[at0.56]|value": "local::at0.33|Single|",
  "/content[openEHR-EHR-ACTION.service-yoga.v0]/time|value": "1900-01-01T00:00:00Z",
  "/context/health_care_facility|identifier": "123456-123",
  "/context/health_care_facility|name": "FACILITY",
  "/context/location": "TEST LAB",
  "/context/setting": "openehr::238|Other Care|",
  "/context/start_time": "2017-07-26T11:21:23.164+05:30",
  "/context/participation:0|function": "Oncologist",
  "/context/participation:0|name": "Composer",
  "/context/participation:0|identifier": "1234-5678",
  "/context/participation:0|mode": "face-to-face communication::openehr::216",
  "/language": "en",
  "/territory": "GB"
}
```
Error
```
 #1.0.0 Invocation exception to method:create:org.jooq.exception.DataAccessException: SQL [insert into &quot;ehr&quot;.&quot;participation&quot; (&quot;event_context&quot;, &quot;performer&quot;, &quot;function&quot;, &quot;mode&quot;, &quot;sys_transaction&quot;) values (?, ?, ?, ?, cast(? as timestamp)) returning &quot;ehr&quot;.&quot;participation&quot;.&quot;id&quot;]; ERROR: insert or update on table &quot;participation&quot; violates foreign key constraint &quot;participation_event_context_fkey&quot;
  Detail: Key (event_context)=(0a135c2b-8db6-4053-90e7-5c0cd7a0ef07) is not present in table &quot;event_context&quot;.
```

**Comment by dileep-ehr** [comment] 2017-07-26 06:44
I have been using the Uberjars and have not setup a development environment. Will try to set it up, compile the new code and try.

**Comment by dileep-ehr** [comment] 2017-07-28 10:42
If you have any sample template where you are able to commit with participation data, please share the opt and composition files for me to test on my server?

**Comment by dileep-ehr** [comment] 2017-07-28 10:53
Do you have any documentation about setting up a development environment that I can use? I have seen that you have done a lot of work in that area recently

**Comment by chevalleyc** [comment] 2018-05-14 02:28
Closing this issue due to no activity.  If the issue is not yet resolved or requires additional work, you may reopen it or open a new CR.

**Closed by chevalleyc** 2018-05-14 02:28 UTC
