### ISSUE TITLE
Problem with date_time constrained to 'Date only' 

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#47] opened 2017-09-18 09:32 UTC
I have a use case where i need to record only date and not time. So I use the date_time datatype and constrain it to 'Date only'. But I am having problem with committing this opt. I am using archetype editor and template designer for creating the opt.

If the field is not constrained (Allow all), the example file returns like below and I am able to commit
` "food_habits/current_food_habits:0/food_habits:0/per_episode/episode_start": "1900-01-01T00:00:00.000Z",`

If I constrain the same field to 'date only', the example returns as below and the commit fails (even with the data in the example)
```
"food_habits/current_food_habits:0/food_habits:0/per_episode/episode_start": {
    "iLocalMillis": -2208988800000,
    "iChronology": {
      "iBase": {
        "iMinDaysInFirstWeek": 4
      }
    }
  },
```
Any pointers?

**Comment by freshehr** [comment] 2017-09-19 10:25
Hi Dileep,

My own practice is not to pre-constrain the date constraint, even where I know that date-only is required. There is nothing wrong with what you are doing- whether the issue is with the tooling or with Ethercis I am not sure but TBH I would take the easy way out and just apply the constraint in the UI :)

**Comment by dileep-ehr** [comment] 2017-09-19 11:54
Dear Ian,

Thanks for the input. I have also been working around the problem as you
are suggesting. However I thought it best to document my observations so
that when time permits, it can be looked into.

Dileep V S
Founder
HealtheLife Ventures LLP
+91 9632888113
103, Innovation Centre, IIIT, Electronics City, Bangalore 560100,
healthelife.in

On 19-Sep-2017 3:55 PM, "Ian McNicoll" <notifications@github.com> wrote:

Hi Dileep,

My own practice is not to pre-constrain the date constraint, even where I
know that date-only is required. There is nothing wrong with what you are
doing- whether the issue is with the tooling or with Ethercis I am not sure
but TBH I would take the easy way out and just apply the constraint in the
UI :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ethercis/ethercis/issues/47#issuecomment-330497239>,
or mute
the thread

**Comment by tony-shannon** [comment] 2017-10-13 11:11
closing this @dileep-ehr on advice from @chevalleyc  , please reopen if any related issues

**Closed by tony-shannon** 2017-10-13 11:11 UTC
