### ISSUE TITLE
Please explain what ehrxml.jar library is and provide access to its sources

### ISSUE THREAD

**Issue by serefarikan** [ethercis/ethercis#85] opened 2017-12-12 16:48 UTC
This library is used by servicemanager component but the readme does not point at its sources like the others. Please provide access to its sources if possible, preferably with the instruction(s) used to generate it presumably using xmlbeans

**Comment by chevalleyc** [comment] 2017-12-14 04:15
It is historical and should be phased out.

**Comment by tony-shannon** [comment] 2017-12-19 12:51
thanks @chevalleyc
@serefarikan Christian suggests this can be closed after recent discussion.
Please add any more detail you think is needed before we do so.
I'll close this issue shortly
Thanks, T
PS This may be the kind of question that could be shared on the etherCIS gitter chatroom, so we can consider moving the discussion there
https://gitter.im/Ripple-Foundation/EtherCIS

**Comment by chevalleyc** [comment] 2018-05-14 02:27
Closing this issue due to no activity.  If the issue is not yet resolved or requires additional work, you may reopen it or open a new CR.

**Closed by chevalleyc** 2018-05-14 02:27 UTC
Labels: question
