### ISSUE TITLE
Please explain the contents of ecis-openehr.jar library and provide access to its contents

### ISSUE THREAD

**Issue by serefarikan** [ethercis/ethercis#86] opened 2017-12-12 16:50 UTC
This library is included in the installation package but I could not find any references to its use or its contents. The only place I've seen it referenced is set_template_table.sh script

**Comment by chevalleyc** [comment] 2017-12-14 04:13
It is a hacked openEHR java-libs archive. This is currently under resolution with CR#60. For info,  the current java-libs does rely on a composition build process that does not allow caching and public setters on RM object attributes.

**Comment by tony-shannon** [comment] 2017-12-19 12:51
thanks @chevalleyc
@serefarikan Christian suggests this can be closed after recent discussion.
Please add any more detail you think is needed before we do so.
I'll close this issue shortly
Thanks, T
PS This may be the kind of question that could be shared on the etherCIS gitter chatroom, so we can consider moving the discussion there
https://gitter.im/Ripple-Foundation/EtherCIS

**Comment by chevalleyc** [comment] 2018-05-14 02:19
Closing this issue due to no activity.  If the issue is not yet resolved or requires additional work, you may reopen it or open a new CR.

**Closed by chevalleyc** 2018-05-14 02:19 UTC
Labels: question
